name: Functional Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch: # Allow manual triggering

jobs:
  functional-tests-ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 10 # Longer timeout for functional tests
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Run Functional Tests
      run: dotnet test PushDeliveredQueue.FunctionalTests --no-build --verbosity normal --configuration Release --logger "console;verbosity=detailed" --collect:"XPlat Code Coverage" --results-directory ./functional-coverage-results/
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: functional-test-results-ubuntu
        path: ./functional-coverage-results/
        retention-days: 30
        
    - name: Generate functional coverage report
      run: |
        reportgenerator \
          -reports:./functional-tests/TestResults/*/coverage.cobertura.xml \
          -targetdir:./functional-coverage-report \
          -reporttypes:HtmlInline_AzurePipelines;Cobertura
        
    - name: Upload functional coverage report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: functional-coverage-report-ubuntu
        path: ./functional-coverage-report/
        retention-days: 30
